src/main/java/pt/ulht/es/todomanager/domain/Todo.java
package pt.ulht.es.todomanager.domain;

import java.util.Comparator;

import org.joda.time.DateTime;

public class Todo extends Todo_Base {

	public Todo(String todoText) {
		setCreationTimestamp(new DateTime());
		setText(todoText);
	}

	public void complete() {
		setCompletionTimestamp(new DateTime());
	}

	public void uncomplete() {
		setCompletionTimestamp(null);
	}

	public static class CreationDateComparator implements Comparator<Todo> {

		public int compare(Todo o1, Todo o2) {
			return o1.getCreationTimestamp().compareTo(o2.getCreationTimestamp());
		}
	}

	public void toggle() {
		if (isCompleted()) {
			uncomplete();
		} else {
			complete();
		}
	}

	public boolean isCompleted() {
		return getCompletionTimestamp() != null;
	}

	public void delete() {
		setTodoList(null);
		super.deleteDomainObject();
	}

}

src/main/java/pt/ulht/es/todomanager/domain/TodoList.java
package pt.ulht.es.todomanager.domain;

public class TodoList extends TodoList_Base {

	public TodoList() {
		setTodoManager(TodoManager.getInstance());
	}

	public void addTodo(String todoText) {
		addTodo(new Todo(todoText));
	}

	public void delete() {
		for (Todo todo : getTodoSet()) {
			todo.delete();
		}
		setTodoManager(null);
		super.deleteDomainObject();
	}
}

src/main/java/pt/ulht/es/todomanager/domain/TodoManager.java
package pt.ulht.es.todomanager.domain;

import pt.ist.fenixframework.FenixFramework;

public class TodoManager extends TodoManager_Base {

	public static TodoManager getInstance() {
		return FenixFramework.getRoot();
	}

}

src/main/java/pt/ulht/es/todomanager/controller/NotFoundController.java
package pt.ulht.es.todomanager.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
public class NotFoundController {

    @RequestMapping(method=RequestMethod.GET, value="/*")
    public String handlePageNotFound() {
        return "redirect:/";
    }
    
}

src/main/java/pt/ulht/es/todomanager/controller/TodoListController.java
package pt.ulht.es.todomanager.controller;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import pt.ist.fenixframework.pstm.AbstractDomainObject;
import pt.ulht.es.todomanager.domain.Todo;
import pt.ulht.es.todomanager.domain.TodoList;
import pt.ulht.es.todomanager.domain.TodoManager;

@Controller
public class TodoListController {

	@RequestMapping(method = RequestMethod.GET, value = "/")
	public String listTodoLists(Model model) {
		model.addAttribute("todoLists", TodoManager.getInstance().getTodoListSet());
		return "listTodoLists";
	}

	@RequestMapping(method = RequestMethod.GET, value = "/todos/{id}")
	public String toggleTodo(@PathVariable("id") String id) {
		Todo todo = AbstractDomainObject.fromExternalId(id);
		todo.toggle();
		return "redirect:/lists/" + todo.getTodoList().getExternalId();
	}

	@RequestMapping(method = RequestMethod.GET, value = "/lists/{id}")
	public String listTodos(@PathVariable("id") String id, Model model) {
		TodoList todoList = AbstractDomainObject.fromExternalId(id);
		List<Todo> todoSortedList = new ArrayList<Todo>(todoList.getTodoSet());
		Collections.sort(todoSortedList, new Todo.CreationDateComparator());
		model.addAttribute("todoList", todoList);
		model.addAttribute("todoSortedList", todoSortedList);
		return "listTodos";
	}

	@RequestMapping(method = RequestMethod.GET, value = "/lists/{id}/delete")
	public String deleteTodoList(@PathVariable("id") String id) {
		TodoList todoList = AbstractDomainObject.fromExternalId(id);
		todoList.delete();
		TodoManager.getInstance().removeTodoList(todoList);
		return "redirect:/";
	}

	@RequestMapping(method = RequestMethod.POST, value = "/lists")
	public String createTodoList(Model model) {
		TodoList todoList = new TodoList();
		return "redirect:/lists/" + todoList.getOid();
	}

	@RequestMapping(method = RequestMethod.POST, value = "/lists/{id}")
	public String createTodo(@PathVariable("id") String id, @RequestParam Map<String, String> params) {
		String todoText = params.get("todoText");
		TodoList todoList = AbstractDomainObject.fromExternalId(id);
		todoList.addTodo(todoText);
		return "redirect:/lists/{id}";
	}
}

src/main/webapp/WEB-INF/jsp/common/libs.jsp
<link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="/static/css/style.css" />
<script type="text/javascript" src="/static/js/bootstrap.js"></script>

src/main/webapp/WEB-INF/jsp/listTodoLists.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>List</title>
		<%@ include file="/WEB-INF/jsp/common/libs.jsp" %>
	</head>
	<body>
		
		<div class="container">
			<h1>Listas de ToDos</h1>
			<table class="table table-striped table-bordered table-condensed">
				<thead>
					<tr>
						<th style="width: 80%">Lista</th>
						<th style="width: 20%; text-align: center">Acções</th>
					</tr>
				<tbody>
				<c:forEach var="todoList" items='${todoLists}'>
					<tr>
						<td><a href="/lists/${todoList.oid}">${todoList.oid}</a></td>
						<td style="text-align: center"><a class="btn btn-mini btn-danger" href="/lists/${todoList.oid}/delete"><i class="icon-trash icon-white"></i> Apagar</a></td>
					</tr>
				</c:forEach>
				</tbody>
			</table>
			<p class="pull-right">
				<form method="POST" action="/lists">
					<button type="submit" class="btn btn-success"><i class="icon-edit icon-white"></i> Criar Nova Lista</button>
				</form>
			</p>
		</div>
	</body>
</html>

src/main/webapp/WEB-INF/jsp/listTodos.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Todo List ${todoList.oid}</title>
		<%@ include file="/WEB-INF/jsp/common/libs.jsp" %>
	</head>
	<body>
		
		<div class="container">
			<ul>
			<c:forEach items="${todoSortedList}" var="todo">
				<c:if test="${todo.completed}">
				<li><a href="/todos/${todo.oid}"><del>${todo.text}</del></a></li>
				</c:if>
				<c:if test="${!todo.completed}">
				<li><a href="/todos/${todo.oid}">${todo.text}</a></li>
				</c:if>
			</c:forEach>
			</ul>
			<form method="POST" action="/lists/${todoList.oid}">
				<input type="text" class="input-xlarge input-todo" placeholder="ex: Fazer o projecto de ES" name="todoText" autofocus />
	  		</form>
		</div>
	</body>
</html>